### ISSUE TITLE
'More info' links need better link text

### ISSUE THREAD

**Issue by ndorfin** [ndorfin/SouthernSunQueenBees#32]
We need more text in the link to better describe where the link goes.
e.g. 

'More info about our instrumentally-inseminated queen bees'

We could use a screenreader-only class to hide all the text after 'More info'. e.g.:

```html
<a>
  More info<span class="screenreader-only"> about our instrumentally-inseminated queen bees</span>
</a>
```

This will be good for at least 2 reasons:

- Better keyword usage associated with the link's URL
- Better accessibility support for keyboard screenreader users

**Comment by nickmangos** [comment]
I implemented a solve in the redesign branch that uses `aria-labelledby` to connect the `h3` to the links for screen readers. Now they read as a list of products under the Products heading which I think makes sense while navigating.
`<li itemscope itemtype="http://schema.org/Product" class="product-card">
  <img src="<%= product.card_icon.url %>" alt="<%= product.card_icon.description %>">
  <h3 id="<%= product.slug %>"><%= product.card_title %></h3>
  <p><%= product.card_description %></p>
  <a class="product-card__link" aria-labelledby="<%= product.slug %>" href="/products/<%= product.slug %>">More Info</a>
</li>`
Tested using Voice Over. What are your thoughts?

**Comment by ndorfin** [comment]
I'm not sure how well-supported that is in the various assistive devices.

Does it work with VoiceOver's link rotor?

The screenreader-only class technique is well-established and supported, and we'd have the keywords in the link text.

Do you want me to implement it?

**Comment by nickmangos** [comment]
It works with the VO link rotor. After some research it is inconclusive, so feel free to replace it if you see fit.

**Comment by ndorfin** [comment]
Fixed
