### ISSUE TITLE
List styles have been removed for content/rich-text blocks

### ISSUE THREAD

**Issue by ndorfin** [ndorfin/SouthernSunQueenBees#33]
Unordered lists have had their styles stripped off in content blocks such as the 'Body of content' in a page.

e.g. in the [Mated Queen Bees product page](https://southernsun.co.nz/products/mated-queen-bees/):

<img width="510" alt="Screenshot 2024-12-02 at 12 10 47 PM" src="https://github.com/user-attachments/assets/b37e3ab9-5fd8-4307-bc94-096a69d2e789">

**Comment by ndorfin** [comment]
Thanks @nickmangos

**Comment by ndorfin** [comment]
@nickmangos Are you planning another merge soon?

**Comment by nickmangos** [comment]
@ndorfin I've submitted a pull request that appears ready to auto merge if you are happy to pull the trigger.
